### ISSUE TITLE
Why count answer zero is changed to one

### ISSUE THREAD

**Issue by SunDoge** [YunseokJANG/tgif-qa#12]
I happen to notice that you use `max(count_answer, 1)` here [code/gifqa/data_util/tgif.py#L561](https://github.com/YunseokJANG/tgif-qa/blob/master/code/gifqa/data_util/tgif.py#L561) but don't know why.

If one gif contains no action mentioned in question, the answer should be 0, right? Is there any reason changing them to 1?

**Comment by YunseokJANG** [comment]
Hi, @SunDoge
Thank you for your interest in our work.

We understand what you want to point out, but there is another thing you need to think of, which is the distance between possible answers; all the other answer choices except 0 (so, from 2 to 10) have a numerical gap of one. Therefore, in order to keep the fairness with other possible answer choices, we match the distance by setting it to 1.

Regards,
Authors of TGIF-QA
