### ISSUE TITLE
What is the model size of the st-vqa model

### ISSUE THREAD

**Issue by czqInNanjing** [YunseokJANG/tgif-qa#15]
Hello, thank you for your great work.
We are doing research upon your projects and we are doing comparisons of model size/trainable parameter size/.
Since the code is based on Python2 and rather old tensorflow, I fail to run the code.
So I wonder if you have ever recorded the model size of your model?
Please inform me if you have. Thank you very much!

**Comment by YunseokJANG** [comment]
Hi @czqInNanjing,
Frankly, I haven't computed the exact size for the st-vqa model. However, since we've shared the checkpoint, I think you can get the exact number by checking our shared checkpoint (You may able to read the hyperparameters in the checkpoint via any third-party toolkit).

Regards,
Yunseok
