### ISSUE TITLE
Why the result is different from paper?

### ISSUE THREAD

**Issue by Apm5** [YunseokJANG/tgif-qa#16]
The results in the READEME.md are quite different from those in the paper. Why? 

What optimizations have been made in the code?

**Comment by YunseokJANG** [comment]
Hi @Apm5,
First of all, thank you for your interest in our work. I checked the performance of our up-to-date CVPR work [link](https://arxiv.org/pdf/1704.04497.pdf), and the number is matched with this. As we mentioned in the last paragraph of Section 1, we've increased the size of our dataset, and that was the reason of the updated performance. 

Regards,
- Yunseok

**Comment by Apm5** [comment]
@YunseokJANG Thank you for reply.
I'm following this [link](http://openaccess.thecvf.com/content_cvpr_2017/html/Jang_TGIF-QA_Toward_Spatio-Temporal_CVPR_2017_paper.html), which is Google scholar search result.

**Comment by YunseokJANG** [comment]
@Apm5  Thanks for mentioning this. I tried to change the link in my Google Scholar profile, to make less confusion, but I failed. Sorry.

By the way, at the same time, I would like to recommend to check arXiv if you want to check what is the most recent one. Because the camera-ready version cannot be changed (by definition), people update their results on arXiv if there is any.
