### ISSUE TITLE
A serious problem on TGIF-QA dataset

### ISSUE THREAD

**Issue by eustcPL** [YunseokJANG/tgif-qa#18]
I only use the answer information and get very high accuracies (over 90%) on two Multi-Choice tasks (Action and Transition).

  I used four different codes (HGA, LAD-Net, HCRN, ours) to investigate the problem and the result are consistent. I only use the candidate answers information. In details, I generate a vector for each candidate (word embedding + RNNs). Then, I sum all the candidate answer vectors to generate an answer representation and I fuse it with each candidate vector. Finally, I use a classifier to predict the answer probabilities.

  I notice that you collect the ground-truth answer by workers and generate other candidates by starting with selecting different verbs. The similarities of these verbs with the verb from the answer phrase are smaller than the 50th percentile. The pattern between the ground-truth answer and other candidates is certain. So, I only select the first word (verb) of the each answer option and the result is similar. I think I have found a way to trigger the failure mode of the dataset.

**Comment by YunseokJANG** [comment]
Hi, eustcPL.
First of all, sorry for my late follow-up. I thought that a reply was given to this matter, but just realized it was not. I was swamped with multiple works during this fall semester.

As for your question, I think it could be a common issue in any vision and language tasks/datasets. Once a person who knows how the answer keys were generated, he or she could attempt to solve a specific task with a powerful language representation by editing the original loss equipped with prior knowledge. In other words, if some tasks don’t include enough biases to grasp a hint, like the repetition task of the TGIF-QA dataset, it is almost impossible to solve them. Because TGIF-QA is designed to solve all four given tasks to measure how well a model comprehends video and language information, I believe it would not harm the core meaning of the dataset. However, as a researcher’s point of view, if anyone wants to create a new dataset, I think it is a good reminder for them to carefully add the wrong answer choices once those items originate from a set of heuristics/biases. Furthermore, I believe this would be an insightful claim to the reviewers in the vision and language domain not to be biased solely by the numbers. Hence, I would like to add a note in the readme file if you would like to share your work on arXiv.

Thanks for sharing this issue, and sorry for my late reply.
Regards,
- Yunseok Jang
