### ISSUE TITLE
Error in vocabulary build_word_vocabulary 

### ISSUE THREAD

**Issue by shwetabhardwaj44** [YunseokJANG/tgif-qa#2]
There is some issue with the shape of GloVe Embeddings. 

Traceback (most recent call last):
  File "main.py", line 85, in <module>
    train_dataset.load_word_vocabulary()
  File "/scratch/tgif-qa/code/gifqa/data_util/tgif.py", line 252, in load_word_vocabulary
    self.build_word_vocabulary()
  File "/scratch/tgif-qa/code/gifqa/data_util/tgif.py", line 235, in build_word_vocabulary
    glove_matrix[i,:] = w_embed
ValueError: could not broadcast input array from shape (384) into shape (300)

**Comment by YunseokJANG** [comment]
Hi, Shweta.
As I answered it via email, this issue is related to the recent update of [spaCy Package]( https://spacy.io/models/en#en_vectors_web_lg).

Please replace 'en_glove_cc_300_1m_vectors' in [our code](https://github.com/YunseokJANG/tgif-qa/blob/master/code/gifqa/data_util/tgif.py#L226) to 'en_vectors_web_lg'.

Regards,
Yunseok

**Comment by shwetabhardwaj44** [comment]
Replacing : 
**nlp = spacy.load('en', vectors='en_glove_cc_300_1m_vectors')** 
with
**nlp = spacy.load('en_vectors_web_lg')**
in code/gifqa/data_util/tgfi.py : build_word_vocabulary
worked for me
