### ISSUE TITLE
Unable to open object

### ISSUE THREAD

**Issue by liurunsmileliu** [YunseokJANG/tgif-qa#21]
![error](https://user-images.githubusercontent.com/80946535/114973842-d7b17d00-9eb3-11eb-9869-0965d731dc72.png)

**Comment by YunseokJANG** [comment]
Dear @liurunsmileliu,
Thanks for sharing your error message. I cannot 100% sure about this case right now (because it works for more than three years, and I haven't seen this before), but I would like to note two things to check:

1. (most likely) the way to handle the h5 file in h5py lib may have changed. If that's the case, could you install a lower version of the h5py file, like h5py==2.5.0, or a little bit higher one? (hint/warning: this codebase was implemented around four years from now)

2. (additional recommendation) I also recommend you to check whether the h5 files are available to open/read, simply by opening them (and accessing some values with a list of keys) with a few lines of code in the Python shell (not with our codebase).

I hope this helps resolve your issue.

Regards,
Yunseok

**Comment by liurunsmileliu** [comment]
Sorry，I try it.But this error still exists.


Lrunzhi

发件人: Yunseok JANG
发送时间: 2021年4月16日 13:44
收件人: YunseokJANG/tgif-qa
抄送: liurunsmileliu; Mention
主题: Re: [YunseokJANG/tgif-qa] Unable to open object (#21)

Dear @liurunsmileliu,
Thanks for sharing your error message. I cannot 100% sure about this case right now (because it works for more than three years, and I haven't seen this before), but I would like to note two things to check:
1. (most likely) the way to handle the h5 file in h5py lib may have changed. If that's the case, could you install a lower version of the h5py file, like h5py==2.5.0, or a little bit higher one? (hint/warning: this codebase was implemented around four years from now)
2. (additional recommendation) I also recommend you to check whether the h5 files are available to open/read, simply by opening them (and accessing some values with a list of keys) with a few lines of code in the Python shell (not with our codebase).
I hope this helps resolve your issue.
Regards,
Yunseok

**Comment by YunseokJANG** [comment]
Thanks for your follow-up message. I reinstall/rerun the codebase on a clean new instance for a double-check, and I think my previous comments are still valid.

1. In my case, h5py and pandas versions were causing an issue in loading the feature files. I was able to load after setting h5py, Pandas, and NumPy to 2.6.0, 0.19.2, and 1.15.1.

2. Please try to open the h5py file from your python terminal if you still failed to load. 

Regards,
Yunseok Jang

**Comment by YunseokJANG** [comment]
Dear @liurunsmileliu ,
I just finished clean installing everything on a new instance, and I was able to run both training and test without any errors. To prevent any versioning issue, I updated the installation manual and added the 'static_requirements.txt' file. Please re-clone this repository and reinstall packages. Thanks for your quick follow-ups, by the way.

Regards,
- Yunseok Jang

**Comment by liurunsmileliu** [comment]
Ok this problem has solved. But when I run python main. py --task=Action --name=SpTp and python main. py --task=Count --name=SpTp throw no tgif-resof-res5c. hdf5
I want to know how to get this feature 
发自我的iPhone

**Comment by YunseokJANG** [comment]
Due to the feature size issue, we failed to upload few features, [as we noted in the README file](https://github.com/YunseokJANG/tgif-qa/tree/master/code#pre-processing-the-visual-features). If you need those missing features, then you need to download the GIF files [from the links in the README](https://github.com/YunseokJANG/tgif-qa/tree/master/dataset#downloading-gif-files) and preprocess them from your own.
