### ISSUE TITLE
Code to extract video representation

### ISSUE THREAD

**Issue by YuanEZhou** [YunseokJANG/tgif-qa#4]
Hi @YunseokJANG, Thanks for your excellent code. Can you release the code to extract video representation?

**Comment by YunseokJANG** [comment]
Hi, @YuanEZhou . 
First of all, thank you for your interest in our project.

To be honest, we failed to find the scripts for extracting the features, but we wrote all the details in [our Github repository](https://github.com/YunseokJANG/tgif-qa/tree/master/code#pre-processing-the-visual-features); Since both [C3D](https://github.com/facebook/C3D) and [ResNet152](https://github.com/KaimingHe/deep-residual-networks) provide official checkpoints, and people upload their own scripts for extraction, you may able to obtain the feature easily. Plus, for non-spatial features, we've uploaded and shared the links for them [in here](https://github.com/YunseokJANG/tgif-qa/tree/master/dataset#downloading-gif-files).

Regards,
Yunseok Jang
