### ISSUE TITLE
Error in the  script save-frames.sh

### ISSUE THREAD

**Issue by FloretCat** [YunseokJANG/tgif-qa#7]
Hi @YunseokJANG,

Thanks for your great work.
But when I use the script 'save-frames.sh' for extracting frames, a huge number of duplicated frames are produced  for some gifs , such as 'tumblr_npe0ojjyfp1u2w06yo1_250.gif', 
'tumblr_no15754JCM1tgouwlo1_250.gif'.
I have replaced the line "ffmpeg -i "$file" "$destination/%d.jpg";" in the script with "ffmpeg -i "$file" -vsync 0 "$destination/%d.jpg" to remove duplicated frames, but I do not know whether this modification is exactly correct.
So, I think it is necessary to let you know this issue.

Look forward to your reply!

**Comment by YunseokJANG** [comment]
Hi, @FloretCat 
First of all, thank you for your interest in our dataset.

I just checked the script (which is added quite recently) with two files that you mentioned, and I faced the same issue that you've mentioned. More specifically, this problem happens when the header of a gif file is somewhat irregular.

I agree that your suggestion avoids such an issue in those cases. ( cf. [a similar question in StackOverflow](https://stackoverflow.com/questions/50420985/ffmpeg-not-extracting-all-the-frames-from-a-video) ) Therefore, relating to this issue, would you mind if I ask you to create a pull request for it?

Regards,
Yunseok

**Comment by FloretCat** [comment]
Hi, @YunseokJANG 

Thanks for your valuable reply!
I am very glad to know the reason for this issue.
Again, I am grateful for your great work!

Many thanks
FloretCat
